---
- name: Configure K3s control plane
  hosts: control_plane
  become: yes
  gather_facts: no

  tasks:

    - name: Create K3s configuration directory
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        mode: "0755"

    - name: Disable Traefik and ServiceLB
      ansible.builtin.copy:
        dest: /etc/rancher/k3s/config.yaml
        mode: "0600"
        content: |
          disable:
            - traefik
            - servicelb

    - name: Restart K3s
      ansible.builtin.systemd:
        name: k3s
        state: restarted
        daemon_reload: yes

    - name: Wait for Kubernetes API
      ansible.builtin.command:
        cmd: k3s kubectl get nodes
      register: k3s_status
      retries: 30
      delay: 5
      until: k3s_status.rc == 0
      changed_when: false
